name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Fix .npmrc
        run: sed -i 's/\${GITHUB_REGISTRY_TOKEN}/'"${GITHUB_REGISTRY_TOKEN}"'/' .npmrc
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Build packages
        run: yarn build:packages

      - name: Create release Pull request or Publish npm
        id: changesets
        uses: changesets/action@master
        with:
          publish: yarn release
